name: Automated Python Playwright Testing

on:
    push:
        branches:
            - "**"

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.12.5"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install lxml playwright
                  playwright install

            # Run tests using custom JSON test runner
            - name: Run tests and output to JSON file
              run: |
                  mkdir -p test_results  # Create directory for test results
                  python automated-testing-run-tests.py

            # Upload test results as an artifact
            - name: Upload test results
              uses: actions/upload-artifact@v4
              with:
                  name: test-results
                  path: test.results.json

            # Fail the build if any tests failed or if no tests were run
            - name: Check for test failures
              run: |
                  if [ -f test.results.json ]; then
                      if grep -q '"status": "failed"' test.results.json; then
                          echo "Tests failed"
                          exit 1
                      else
                          echo "Tests passed"
                      fi
                  else
                      echo "No tests were run"
                      exit 1
                  fi
