name: Automated Python Playwright Testing

on:
    push:
        branches:
            - "**"

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.12.5"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install lxml playwright unittest-xml-reporting xmltodict
                  playwright install

            - name: Run tests with Playwright and unittest
              run: |
                  python -m xmlrunner discover -s tests -p "test_*.py" -o test-reports
                  python scripts/automated-testing-save-results.py
              continue-on-error: true

            - name: Upload test results
              uses: actions/upload-artifact@v4
              with:
                  name: test-results
                  path: test.results.json

            - name: Check if any tests ran
              run: |
                  if grep -q '"total": 0,' test.results.json; then
                    echo "No tests were run"
                    exit 1
                  fi

            - name: Check test results
              run: |
                  if grep -q '"failed":' test.results.json; then
                    echo "Tests failed"
                    exit 1
                  else
                    echo "Tests passed"
                  fi
