name: W3C Validation

on:
    push:
        branches:
            - "**"

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            # Checkout code
            - name: Checkout code
              uses: actions/checkout@v3

            # Set up Python
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12.5"

            # Install dependencies
            - name: Install dependencies
              run: |
                  pip install requests

            # Validate HTML with W3C Validator API
            - name: Validate HTML with W3C Validator API
              run: |
                  mkdir -p validation_results
                  validation_failed=0
                  for file in $(find . -name "*.html"); do
                      echo "Validating $file"
                      response=$(curl -s -F "out=json" -F "content=@$file" https://validator.w3.org/nu/?parser=html5)
                      if [ $? -ne 0 ]; then
                          echo "Error fetching validation results for $file"
                          validation_failed=1
                          continue
                      fi
                      echo "$response" > "validation_results/w3c-validation-$(basename $file .html).json"
                      if echo "$response" | grep -q "error"; then
                          echo "Error in response for $file: $response"
                          validation_failed=1
                          continue
                      fi
                      errors=$(echo "$response" | python3 -c "import sys, json; data = json.load(sys.stdin); print(len([msg for msg in data['messages'] if msg['type'] in ['error', 'warning']]))")
                      if [ "$errors" -gt 0 ]; then
                          echo "Validation issues found in $file"
                          validation_failed=1
                      fi
                  done
                  echo "$validation_failed" > validation_results/html_validation_failed_flag.txt

            # Validate CSS with W3C Validator API
            - name: Validate CSS with W3C Validator API
              run: |
                  mkdir -p validation_results
                  validation_failed=0
                  for file in $(find . -name "*.css"); do
                      echo "Validating $file"
                      response=$(curl -s -F "out=json" -F "text=@$file" https://jigsaw.w3.org/css-validator/validator)
                      if [ $? -ne 0 ]; then
                          echo "Error fetching validation results for $file"
                          validation_failed=1
                          continue
                      fi
                      echo "$response" > "validation_results/w3c-validation-$(basename $file .css).json"
